Laboratory work #2, Baranov Timofey - 22FPL1
fipl-hse/2023-2-level-labs pull request #112
Opened 2023-10-25 07:46 UTC by tima-baranov

2023-10-31 09:52 UTC, artyomtugaryov requested changes

2023-10-31 09:52 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        if token in punctuation:
looks like we can use single `if`

2023-10-31 09:52 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +    return tuple(tokens)
Can you add some empty lines?

2023-10-31 09:52 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +    return freq_dictionary
the same

2023-10-31 11:25 UTC, tima-baranov commented on lab_2_tokenize_by_bpe/main.py
> +    return tuple(tokens)
Fixed

2023-10-31 11:25 UTC, tima-baranov commented on lab_2_tokenize_by_bpe/main.py
> +    return freq_dictionary
Fixed

2023-11-02 10:38 UTC, artyomtugaryov requested changes

2023-11-02 10:38 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> -import json
Revert, please

2023-11-02 10:38 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +
rm

2023-11-02 12:12 UTC, tima-baranov commented on lab_1_classify_by_unigrams/main.py
> -import json
Fixed

2023-11-02 12:15 UTC, tima-baranov commented on lab_2_tokenize_by_bpe/main.py
> +
Fixed

2023-11-02 12:17 UTC, artyomtugaryov requested changes

2023-11-02 12:17 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +    for i in text.split():
let's rename `i`

2023-11-02 16:28 UTC, tima-baranov commented on lab_2_tokenize_by_bpe/main.py
> +    for i in text.split():
Fixed

2023-11-03 08:06 UTC, closed without merging