Laboratory work #2, Varvara Migacheva - 22FPL2
fipl-hse/2023-2-level-labs pull request #115
Opened 2023-10-28 13:48 UTC by varmig2000

2023-10-31 13:51 UTC, artyomtugaryov requested changes
Very good. What about 6, 8, 10?

2023-11-01 23:54 UTC, varmig2000 commented
I tried...... Sorry. See the first "step 2"

2023-11-02 14:06 UTC, artyomtugaryov requested changes

2023-11-02 14:06 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +    for el in raw_word:
simplify

2023-11-02 14:06 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +                el_list[i] = pair[0] + pair[1]
join

2023-11-03 21:36 UTC, closed without merging