Laboratory work #2, Egor Kostin - 22FPL2
fipl-hse/2023-2-level-labs pull request #117
Opened 2023-11-01 14:31 UTC by egorkostin24

2023-11-02 14:03 UTC, artyomtugaryov requested changes

2023-11-02 14:03 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/target_score.txt
> +0
change it. + start.py

2023-11-02 14:37 UTC, artyomtugaryov requested changes

2023-11-02 14:37 UTC, artyomtugaryov commented on docs/public/tests.md
> +```
revert

2023-11-02 14:37 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +    return frequencies
change start.py and target_score

2023-11-09 12:20 UTC, artyomtugaryov requested changes
Looks like you should merge your branch with upstream/main

2023-11-16 14:33 UTC, artyomtugaryov commented
You have to merge with master

2023-11-16 18:36 UTC, egorkostin24 commented on lab_2_tokenize_by_bpe/target_score.txt
> +0
done

2023-11-16 18:36 UTC, egorkostin24 commented on docs/public/tests.md
> +```
done

2023-11-16 18:36 UTC, egorkostin24 commented on lab_2_tokenize_by_bpe/main.py
> +    return frequencies
done

2023-11-18 17:15 UTC, closed without merging