1
fipl-hse/2023-2-level-labs pull request #12
Opened 2023-09-08 09:34 UTC by Damir-Khamidullin

2023-09-21 11:03 UTC, artyomtugaryov requested changes
Nothing to review yet :(

2023-09-21 11:03 UTC, artyomtugaryov commented on main.py
> +print('Hello, world!')
please, remove the file

2023-09-28 14:03 UTC, artyomtugaryov requested changes

2023-10-01 10:02 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    if (type(predicted) != list or
changed

2023-10-01 10:02 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    if type(tokens) != list or tokens == []:
changed

2023-10-01 10:02 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    for i in text:
done

2023-10-01 10:02 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    if type(text) != str:
changed

2023-10-01 10:02 UTC, Damir-Khamidullin commented on main.py
> +print('Hello, world!')
deleted

2023-10-03 15:19 UTC, artyomtugaryov requested changes

2023-10-03 15:19 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    tokens_list = []
create it after checks

2023-10-03 15:19 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    for symbol in tokens:
too many loops

2023-10-03 15:19 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        else:
let's try without else

2023-10-03 15:19 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    mse = mse_sum / len(predicted)
do not create the variable

2023-10-03 15:19 UTC, artyomtugaryov commented on main.py
> +print('Hello, world!')
no

2023-10-03 17:48 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    mse = mse_sum / len(predicted)
changed

2023-10-03 17:48 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    for symbol in tokens:
changed

2023-10-03 17:49 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    for i in text:
changed

2023-10-03 17:49 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    tokens_list = []
changed

2023-10-03 17:54 UTC, Damir-Khamidullin commented on main.py
> +print('Hello, world!')
is it deleted now?

2023-10-05 13:13 UTC, artyomtugaryov requested changes

2023-10-05 13:13 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    tokens_list = [i for i in text if i.isalpha()]
do not create the variable

2023-10-05 13:13 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        else:
if `symbol` is in `freq_dict` - set 0 and always increment it

2023-10-05 13:13 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    language_profile = {"name": language,
do not create the variable

2023-10-05 13:13 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +
revert

2023-10-05 17:39 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    tokens_list = [i for i in text if i.isalpha()]
changed

2023-10-05 17:39 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +    language_profile = {"name": language,
changed

2023-10-05 17:39 UTC, Damir-Khamidullin commented on lab_1_classify_by_unigrams/main.py
> +
changed

2023-10-08 17:04 UTC, closed without merging