Laboratory work #3, Sonia Zakharova - 21FPL2
fipl-hse/2023-2-level-labs pull request #125
Opened 2023-11-04 13:35 UTC by solonarr

2023-11-04 14:14 UTC, solonarr commented
ломаем и чиним снова и снова

2023-11-09 08:00 UTC, artyomtugaryov requested changes
Strange changes. Need to be updated by the mentor

2023-11-09 08:00 UTC, artyomtugaryov commented on config/spellcheck/.wordlist_en.txt
> -data
revert

2023-11-10 06:08 UTC, solonarr commented on config/spellcheck/.wordlist_en.txt
> -data
done?????????????????????

2023-11-17 04:43 UTC, artyomtugaryov reviewed
Please, revert all unrelated changes

2023-11-17 04:43 UTC, artyomtugaryov commented on config/stage_1_style_tests/_stage_run_stubgen.sh
> -
revert

2023-11-21 13:21 UTC, artyomtugaryov requested changes
looks like something bad in your request

2023-11-23 15:51 UTC, artyomtugaryov requested changes

2023-11-23 15:51 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +    _end_of_word_token: str
what? Why?

2023-11-23 15:51 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
discard

2023-11-23 15:51 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                result += ' '
fstring

2023-11-24 16:38 UTC, closed without merging