Laboratory work #3, Margarita Velmisova - 22FPL1
fipl-hse/2023-2-level-labs pull request #127
Opened 2023-11-04 19:45 UTC by velgarita

2023-11-09 07:57 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-16 14:10 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        tokens = tokens[:-1]
Why are you doing this?

2023-11-18 20:19 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +        tokens = tokens[:-1]
changed it

2023-11-18 20:22 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +        storage_invert = {ident: token for token, ident in self._storage.items()}
changed it

2023-11-18 20:23 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +            ident = len(self._storage)
I really don't need it, fixed this

2023-11-18 20:24 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +            for token in n_gram:
ok

2023-11-18 20:27 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +            decoded_text += '.'
ok

2023-11-18 20:30 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +        return None
what exactly should I change?

2023-11-18 20:31 UTC, velgarita commented on lab_3_generate_by_ngrams/main.py
> +            self, encoded_corpus: tuple[int, ...]
done

2023-11-21 12:05 UTC, artyomtugaryov requested changes

2023-11-21 12:05 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                context_freq_dict[context] = sum(1 for n_gram_1 in n_grams
count

2023-11-23 15:04 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for token, ident in self._storage.items():
What about this comment?

2023-11-23 15:04 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            if len(tokens) > len_prev:
and this?

2023-11-24 15:14 UTC, merged