Laboratory work #3, Timofey Baranov - 22FPL1
fipl-hse/2023-2-level-labs pull request #128
Opened 2023-11-05 09:17 UTC by tima-baranov

2023-11-09 12:25 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-16 14:38 UTC, artyomtugaryov requested changes
Nothing to review(

2023-11-21 10:38 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-23 12:38 UTC, artyomtugaryov requested changes

2023-11-23 12:38 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                postprocessed_text += '.'
fstring

2023-11-23 12:38 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                postprocessed_text += token
fstring

2023-11-23 19:18 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +        if len(tokenized_text) == tokenized_text.count(self._end_of_word_token):
fixed

2023-11-23 19:19 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +            return None
fixed

2023-11-23 19:19 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +        for token in tokenized_text:
fixed

2023-11-23 19:19 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +        if isinstance(element, str) and len(element) == 1 and element not in self._storage:
fixed

2023-11-23 19:19 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +                postprocessed_text += '.'
fixed

2023-11-23 19:19 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +            elif token == self._end_of_word_token:
fixed

2023-11-23 19:20 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +                postprocessed_text += ' '
fixed

2023-11-23 19:20 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +                postprocessed_text += token
fixed

2023-11-24 06:57 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +        if not text[-1].isalnum() and tokenized_text[-1] != self._end_of_word_token:
fixed

2023-11-24 06:57 UTC, tima-baranov commented on lab_3_generate_by_ngrams/main.py
> +                if element.isalpha():
fixed

2023-11-24 16:41 UTC, closed without merging