Laboratory work #3, Andrey Gusev - 22FPL1
fipl-hse/2023-2-level-labs pull request #130
Opened 2023-11-05 10:57 UTC by AndreyGusev1

2023-11-09 12:04 UTC, artyomtugaryov requested changes

2023-11-09 12:04 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        self._end_of_word_token = '_'
strange constant

2023-11-09 12:04 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            tokenized_text.append('_')
again

2023-11-16 15:30 UTC, AndreyGusev1 commented on lab_3_generate_by_ngrams/main.py
> +        self._end_of_word_token = '_'
fixed

2023-11-16 15:30 UTC, AndreyGusev1 commented on lab_3_generate_by_ngrams/main.py
> +            tokenized_text.append('_')
fixed

2023-11-17 04:46 UTC, artyomtugaryov requested changes

2023-11-17 04:46 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for i, j in enumerate(decoded_corpus):
Better names, please

2023-11-20 09:26 UTC, AndreyGusev1 commented on lab_3_generate_by_ngrams/main.py
> +        for i, j in enumerate(decoded_corpus):
fixed

2023-11-21 11:52 UTC, artyomtugaryov requested changes

2023-11-21 11:52 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not isinstance(text, str) or len(text) == 0:
simplify this: `len(text)==0`

2023-11-21 11:52 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        counter = 0
Wow... check it simply

2023-11-21 11:52 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for keys, values in self._storage.items():
filter

2023-11-23 15:00 UTC, AndreyGusev1 commented on lab_3_generate_by_ngrams/main.py
> +        counter = 0
fixed

2023-11-23 15:33 UTC, artyomtugaryov requested changes

2023-11-23 15:33 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            elif word is ' ' and tokenized_text[-1] != self._end_of_word_token:
just `not word`

2023-11-23 15:33 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                result += '.'
fstring

2023-11-23 16:43 UTC, AndreyGusev1 commented on lab_3_generate_by_ngrams/main.py
> +        for keys, values in self._storage.items():
fixed

2023-11-24 16:42 UTC, closed without merging