Laboratory work #3, Ratmir Akhmatzyanov - 22FPL1
fipl-hse/2023-2-level-labs pull request #135
Opened 2023-11-06 02:59 UTC by Rotmerka

2023-11-09 12:24 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-17 04:45 UTC, artyomtugaryov requested changes

2023-11-17 04:45 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/target_score.txt
> +4
I guess it is not enough

2023-11-21 12:22 UTC, artyomtugaryov requested changes

2023-11-21 12:22 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        lower_list_text = tuple(filter(lambda x: x == " " or str.isalpha, text.lower()))
`x == " "` -> not x

2023-11-21 12:22 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        position = list(self._storage.values()).index(element_id)
tooooo dificult

2023-11-23 15:35 UTC, artyomtugaryov requested changes
The same comments

2023-11-30 13:10 UTC, artyomtugaryov requested changes

2023-11-30 13:10 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not (isinstance(text, str) and text):
where is the implementation?

2023-12-01 05:01 UTC, Rotmerka commented on lab_3_generate_by_ngrams/main.py
> +        return f"{''.join(decoded_corpus).replace(self._end_of_word_token, ' ').capitalize().rstrip()}."
like that?

2023-12-01 19:52 UTC, closed without merging