Laboratory work #3, Arina Savina - 22FPL1
fipl-hse/2023-2-level-labs pull request #139
Opened 2023-11-07 11:10 UTC by a00rina

2023-11-09 12:02 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-21 12:44 UTC, artyomtugaryov requested changes

2023-11-21 12:44 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        alphas = 0
too much... try anather way to chec

2023-11-21 12:44 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for key, value in self._storage.items():
filter

2023-11-21 12:44 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                post_text += ' '
fstring

2023-11-21 12:44 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                post_text += token
.

2023-11-22 19:23 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +        for key, value in self._storage.items():
done

2023-11-22 19:23 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +        alphas = 0
hoped that understood you right

2023-11-23 07:02 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +                post_text += ' '
done, hope it's right)

2023-11-23 15:42 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        # if not isinstance(text, (str | None)):
remove

2023-11-23 15:43 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not post_text:
`return post_text or None`

2023-11-23 17:27 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +        # if not isinstance(text, (str | None)):
done

2023-11-23 17:28 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +        return None
guess I found it)

2023-11-23 17:28 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +        if not post_text:
done

2023-11-23 17:28 UTC, a00rina commented on lab_3_generate_by_ngrams/main.py
> +            self, encoded_corpus: tuple[int, ...]
done

2023-11-24 16:47 UTC, closed without merging