Laboratory work #3, Irina Pereyaslavtseva - 22FPL1
fipl-hse/2023-2-level-labs pull request #148
Opened 2023-11-10 06:40 UTC by iriper

2023-11-17 04:47 UTC, artyomtugaryov requested changes
Nothing to review

2023-11-23 15:34 UTC, artyomtugaryov requested changes

2023-11-23 15:34 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        # if not isinstance(content, dict):
remove

2023-11-23 15:56 UTC, iriper commented on lab_3_generate_by_ngrams/main.py
> +        # if not isinstance(content, dict):
done

2023-11-24 16:53 UTC, closed without merging