Laboratory work #3, Ruslana Zobnina - 22FPL2
fipl-hse/2023-2-level-labs pull request #152
Opened 2023-11-14 19:43 UTC by RuslanaZobnina

2023-11-17 04:31 UTC, artyomtugaryov requested changes
Good start

2023-11-21 12:40 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                return None
too many indents

2023-11-21 12:40 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if tokens == []:
bad check - what about truthy/falsy?

2023-11-21 12:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if text[-1] != "/?;:'-=+.,£#@$%^><*&()":
string.panctuation

2023-11-21 12:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for key, value in self._storage.items():
filter

2023-11-21 12:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            if self.get_id(i) is None:
why do you call `get_id` twice ?

2023-11-21 12:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                postprocess_decoded_text += '.'
fstring

2023-11-21 12:42 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        self._n_gram_size = range(2, 5)
what does this range mean?

2023-11-22 23:48 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +        if text[-1] != "/?;:'-=+.,£#@$%^><*&()":
done

2023-11-22 23:48 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +        for key, value in self._storage.items():
done

2023-11-22 23:49 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +            if self.get_id(i) is None:
fixed

2023-11-22 23:50 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +                postprocess_decoded_text += '.'
done

2023-11-22 23:50 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +        self._n_gram_size = range(2, 5)
fixed

2023-11-22 23:50 UTC, RuslanaZobnina commented on lab_3_generate_by_ngrams/main.py
> +                return None
fixed

2023-11-23 15:41 UTC, artyomtugaryov requested changes

2023-11-23 15:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            elif token == ' ' and len(tokens) > 0 and tokens[-1] != self._end_of_word_token:
just `not token`

2023-11-23 15:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            if token is None:
Why is it specific check for none? not just `not token`?

2023-11-24 16:56 UTC, closed without merging