Laboratory work #3, Ugolnikov Viacheslav - 22FPL1
fipl-hse/2023-2-level-labs pull request #155
Opened 2023-11-16 20:01 UTC by slava-ugolnikov

2023-11-21 10:42 UTC, artyomtugaryov requested changes

2023-11-21 10:42 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +    def __init__(self, end_of_word_token: str, storage: dict) -> None:
Do not change the interface

2023-11-21 10:42 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            elif symbol in ' !?.' \
Only these symbols are punctuation?

2023-11-21 10:42 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +                decoding_list += ' '
again. It is a workaround with magic constants. It is a bad solution

2023-11-21 10:42 UTC, artyomtugaryov commented on seminars/practice_8_inheritance.py
> +    def __init__(self, max_speed: int, colour: str) -> None:
checkout to original version

2023-11-23 12:49 UTC, artyomtugaryov requested changes

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +            elif symbol in '''!"#$%&'()*+, ./\:;<=>?@[]^_`{|}~''' \
Is it all punctuation? Is there reliable way to get punctuation?

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        return None
There is a better way to fix mypy/pylint...

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if None in tokenized_text \
can you check it inside loop and return None as soon as posible

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if element not in self._storage:
what about early return?

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        return result + '.'
fstring

2023-11-23 12:49 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
revert

2023-11-23 12:49 UTC, artyomtugaryov commented on seminars/practice_8_inheritance.py
> +    def __init__(self, max_speed: int, colour: str) -> None:
!

2023-11-23 17:46 UTC, slava-ugolnikov commented on seminars/practice_8_inheritance.py
> +    def __init__(self, max_speed: int, colour: str) -> None:
how can I do that?

2023-11-23 19:22 UTC, slava-ugolnikov commented on lab_3_generate_by_ngrams/main.py
> +        if element not in self._storage:
I tried to do that

2023-11-23 19:22 UTC, slava-ugolnikov commented on lab_3_generate_by_ngrams/main.py
> +        return result + '.'
done

2023-11-24 16:56 UTC, closed without merging