Laboratory work #3, Varvara Migacheva - 22FPL2
fipl-hse/2023-2-level-labs pull request #158
Opened 2023-11-20 17:44 UTC by varmig2000

2023-11-21 11:00 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for letter, identifier in self._storage.items():
again - filter?

2023-11-22 19:52 UTC, varmig2000 commented on lab_3_generate_by_ngrams/main.py
> +        if text[-1] in string.punctuation:
i have removed the first condition

2023-11-22 19:52 UTC, varmig2000 commented on lab_3_generate_by_ngrams/main.py
> +        if len(tokens) == 0:
fixed

2023-11-22 19:53 UTC, varmig2000 commented on lab_3_generate_by_ngrams/main.py
> +        for token in text.lower():
fixed

2023-11-22 20:24 UTC, varmig2000 commented on lab_3_generate_by_ngrams/main.py
> +        for letter, identifier in self._storage.items():
fixed

2023-11-23 15:31 UTC, artyomtugaryov requested changes
please, adress all comments

2023-11-23 19:05 UTC, varmig2000 commented on lab_3_generate_by_ngrams/main.py
> +        if element not in self._storage:
fixed

2023-11-24 16:59 UTC, closed without merging