Laboratory work #2, Maxim Glukhankov - 22FPL1
fipl-hse/2023-2-level-labs pull request #160
Opened 2023-11-22 20:15 UTC by glukhankov

2023-11-23 12:23 UTC, artyomtugaryov requested changes
You implementation is absolutelly the same as in main branch. It is very strange.

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        raw_word: str, start_of_word: str | None, end_of_word: str | None
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        text: str, start_of_word: str | None, end_of_word: str
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int]
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int], pair: tuple[str, str]
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int] | None, num_merges: int
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int], unknown_token: str
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        original_text: str,
revert

2023-11-23 12:23 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        actual: list[tuple[str, ...]], reference: list[tuple[str, ...]]
revert

2023-11-23 17:43 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        raw_word: str, start_of_word: str | None, end_of_word: str | None
done

2023-11-23 17:43 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        text: str, start_of_word: str | None, end_of_word: str
done

2023-11-23 17:44 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int]
done

2023-11-23 17:44 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int], pair: tuple[str, str]
done

2023-11-23 17:44 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        word_frequencies: dict[tuple[str, ...], int] | None, num_merges: int
done

2023-11-23 17:44 UTC, glukhankov commented on lab_2_tokenize_by_bpe/main.py
> +        actual: list[tuple[str, ...]], reference: list[tuple[str, ...]]
all done

2023-11-30 13:36 UTC, artyomtugaryov requested changes

2023-12-01 19:51 UTC, closed without merging