Laboratory work #4, Zakharova Sofja - 21FPL2
fipl-hse/2023-2-level-labs pull request #170
Opened 2023-11-25 11:10 UTC by solonarr

2023-11-30 14:00 UTC, artyomtugaryov requested changes

2023-12-07 13:11 UTC, artyomtugaryov requested changes

2023-12-07 13:11 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                raise ValueError
.

2023-12-14 10:56 UTC, artyomtugaryov requested changes

2023-12-14 10:56 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message

2023-12-17 07:23 UTC, artyomtugaryov requested changes
fix previous comments

2023-12-17 08:21 UTC, solonarr commented on lab_4_fill_words_by_ngrams/main.py
> +                raise ValueError
fixed

2023-12-17 08:21 UTC, solonarr commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
fixed

2023-12-17 08:21 UTC, solonarr commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
fixed

2023-12-19 17:49 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:49 UTC, closed without merging