Laboratory work #4, Margarita Velmisova - 22FPL1
fipl-hse/2023-2-level-labs pull request #174
Opened 2023-11-26 11:42 UTC by velgarita

2023-12-07 12:28 UTC, artyomtugaryov requested changes
Nothing to review

2023-12-14 07:44 UTC, artyomtugaryov requested changes

2023-12-14 07:44 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            elif word[-1] in ['.', '!', '?']:
why not set?

2023-12-14 07:44 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            elif word[-1] in ['.', '!', '?']:
create it once before the loop

2023-12-14 07:44 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        generator_types = {0: 'Greedy Generator', 1: 'Top-P Generator', 2: 'Beam Search Generator'}
this map shoud be in self

2023-12-15 13:20 UTC, velgarita commented on lab_4_fill_words_by_ngrams/main.py
> +        generator_types = {0: 'Greedy Generator', 1: 'Top-P Generator', 2: 'Beam Search Generator'}
changed it

2023-12-15 13:21 UTC, velgarita commented on lab_4_fill_words_by_ngrams/main.py
> +            elif word[-1] in ['.', '!', '?']:
fixed it

2023-12-17 06:41 UTC, artyomtugaryov requested changes

2023-12-17 06:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                tokenized_word.append(word)
use `continue` and remove `else`

2023-12-17 06:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            self, language_model: NGramLanguageModel, word_processor: WordProcessor, p_value: float
revert

2023-12-17 06:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        generator_types = {self.greedy: 'Greedy Generator', self.top_p: 'Top-P Generator',
why is this map not in `__init__`?

2023-12-17 08:30 UTC, velgarita commented on lab_4_fill_words_by_ngrams/main.py
> +                tokenized_word.append(word)
done

2023-12-17 08:30 UTC, velgarita commented on lab_4_fill_words_by_ngrams/main.py
> +            self, language_model: NGramLanguageModel, word_processor: WordProcessor, p_value: float
done

2023-12-17 08:32 UTC, velgarita commented on lab_4_fill_words_by_ngrams/main.py
> +        generator_types = {self.greedy: 'Greedy Generator', self.top_p: 'Top-P Generator',
changed it

2023-12-19 17:51 UTC, closed without merging

2023-12-19 17:51 UTC, vitazaytseva commented
Well done! Good job!