Laboratory work #4, Elena Ermak - 22FPL1
fipl-hse/2023-2-level-labs pull request #176
Opened 2023-11-26 18:16 UTC by ermakelena

2023-12-07 12:31 UTC, artyomtugaryov requested changes

2023-12-14 10:25 UTC, artyomtugaryov requested changes

2023-12-14 10:25 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            if token[-1] in "?!.":
`"?!."` to a variable

2023-12-17 07:10 UTC, artyomtugaryov requested changes

2023-12-17 07:10 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-17 07:10 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
remove

2023-12-17 07:10 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
remove

2023-12-17 07:10 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
remove

2023-12-17 14:32 UTC, ermakelena commented on lab_4_fill_words_by_ngrams/main.py
> +            if token[-1] in "?!.":
done

2023-12-17 14:32 UTC, ermakelena commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
done

2023-12-17 14:33 UTC, ermakelena commented on lab_4_fill_words_by_ngrams/main.py
> +
done

2023-12-17 14:33 UTC, ermakelena commented on lab_4_fill_words_by_ngrams/main.py
> +
done

2023-12-17 14:33 UTC, ermakelena commented on lab_4_fill_words_by_ngrams/main.py
> +
done

2023-12-19 17:52 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:52 UTC, closed without merging