Laboratory work #4, Krivtsov Artyom - 22FPL2
fipl-hse/2023-2-level-labs pull request #179
Opened 2023-11-28 18:39 UTC by artyom6k

2023-12-07 13:36 UTC, artyomtugaryov requested changes
Nothing to review

2023-12-14 10:27 UTC, artyomtugaryov requested changes
What about start.py?

2023-12-14 10:27 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> -
revert

2023-12-14 10:27 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message to the error

2023-12-14 10:27 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            if word[-1] in '!?.':
`!?.` to a variable

2023-12-14 10:27 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        return tuple(clean_txt)
add empty line

2023-12-17 07:15 UTC, artyomtugaryov requested changes
Where is the start.py?

2023-12-17 16:54 UTC, artyom6k commented on lab_4_fill_words_by_ngrams/main.py
> +        return tuple(clean_txt)
Done

2023-12-17 16:56 UTC, artyom6k commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
Done

2023-12-17 16:57 UTC, artyom6k commented on lab_4_fill_words_by_ngrams/main.py
> -
Done

2023-12-19 17:54 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:54 UTC, closed without merging