Laboratory work #4, Arina Savina - 22FPL1
fipl-hse/2023-2-level-labs pull request #180
Opened 2023-11-29 12:22 UTC by a00rina

2023-12-14 10:58 UTC, artyomtugaryov requested changes

2023-12-14 10:58 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message

2023-12-17 07:20 UTC, artyomtugaryov reviewed
add messages to errors

2023-12-17 07:20 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-19 17:55 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:55 UTC, closed without merging