Laboratory work #4, Anna Vorontsova - 22FPL2
fipl-hse/2023-2-level-labs pull request #184
Opened 2023-11-30 13:08 UTC by vorontsann

2023-12-14 10:45 UTC, artyomtugaryov requested changes
Not bad

2023-12-14 10:45 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            if element in "?!.":
to the variable, please

2023-12-16 11:33 UTC, vorontsann commented on lab_4_fill_words_by_ngrams/main.py
> +            if element in "?!.":
fixed

2023-12-17 07:25 UTC, artyomtugaryov reviewed
Very good

2023-12-19 17:57 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:57 UTC, closed without merging