Laboratory work #4, Irina Pereyaslavtseva - 22FPL1
fipl-hse/2023-2-level-labs pull request #186
Opened 2023-11-30 14:23 UTC by iriper

2023-12-07 13:37 UTC, artyomtugaryov requested changes

2023-12-07 13:37 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/target_score.txt
> +6
what about pipeline? Is it green?

2023-12-14 10:55 UTC, artyomtugaryov requested changes

2023-12-14 10:55 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/target_score.txt
> +6
It is not enought

2023-12-17 07:17 UTC, artyomtugaryov requested changes

2023-12-17 07:17 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/target_score.txt
> +6
It is not enough

2023-12-19 17:59 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:59 UTC, closed without merging