Laboratory work #4, Damir Khamidullin - 22FPL2
fipl-hse/2023-2-level-labs pull request #189
Opened 2023-12-01 06:42 UTC by Damir-Khamidullin

2023-12-07 12:40 UTC, artyomtugaryov requested changes
Nothing to review

2023-12-14 07:18 UTC, artyomtugaryov reviewed
Add error messages in each raise

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        for symbol in ['.', '!', '?']:
use tuple in this case

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            text = text.replace(symbol, ' ' + self._end_of_word_token)
use fstring

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message to the error

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                tokens.append(word)
Is it some optimization?

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        return text + '.'
fstring

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
.

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                raise ValueError
.

2023-12-14 07:18 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
.

2023-12-17 06:16 UTC, artyomtugaryov requested changes

2023-12-17 06:16 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-17 06:16 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
message

2023-12-17 06:16 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                raise ValueError
message

2023-12-17 06:16 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/start.py
> +    print(generation_1)
remove

2023-12-19 17:59 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 17:59 UTC, closed without merging