Laboratory work #4, Ruslana Zobnina - 22FPL2.
fipl-hse/2023-2-level-labs pull request #195
Opened 2023-12-03 20:23 UTC by RuslanaZobnina

2023-12-07 13:38 UTC, artyomtugaryov requested changes

2023-12-14 10:41 UTC, artyomtugaryov requested changes
What about start.py?

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/target_score.txt
> +6
revert

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                tokens += ' ' + self._end_of_word_token
fstring

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
too

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
oo

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
oo

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
o_O

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
O_o

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
O_O

2023-12-14 10:41 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +
many empty lines

2023-12-17 07:28 UTC, artyomtugaryov reviewed
Very good

2023-12-19 18:02 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 18:02 UTC, closed without merging