Laboratory work #3, Maxim Glukhankov - 22FPL1
fipl-hse/2023-2-level-labs pull request #199
Opened 2023-12-06 13:37 UTC by glukhankov

2023-12-07 13:17 UTC, artyomtugaryov requested changes

2023-12-14 03:37 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +            tokens = [i for i in word if i.isalpha()]
done

2023-12-14 03:38 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +        if not isinstance(decoded_corpus, tuple) or not decoded_corpus:
I tried to change them as much as I could

2023-12-14 03:38 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +        for i in corpus:
thank you

2023-12-14 07:46 UTC, artyomtugaryov requested changes
What about start py? It contains code for 10

2023-12-14 07:46 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for i in corpus:
but name is absolutelly bad

2023-12-14 07:46 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        print(context_freq_dict)
remove

2023-12-14 07:46 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        print(lower_ngram_counts)
remove

2023-12-16 23:00 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +        print(context_freq_dict)
done

2023-12-16 23:00 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +        print(lower_ngram_counts)
done

2023-12-17 06:45 UTC, artyomtugaryov requested changes

2023-12-17 06:45 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not isinstance(decoded_corpus, tuple) or not decoded_corpus:
If you cannot implement it - remove

2023-12-18 11:41 UTC, glukhankov commented on lab_3_generate_by_ngrams/main.py
> +        if not isinstance(decoded_corpus, tuple) or not decoded_corpus:
got it

2023-12-19 18:05 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 18:05 UTC, closed without merging