laboratory work #4, Matyoqubov Ogabek - 22FPL-2.
fipl-hse/2023-2-level-labs pull request #203
Opened 2023-12-08 08:34 UTC by ogabekmatyoqubov

2023-12-14 07:33 UTC, artyomtugaryov requested changes
What about start.py?

2023-12-17 06:53 UTC, artyomtugaryov requested changes
Add message to each error

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                tokens.append(word)
use `continue` and remove `else`

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add message

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +    generation
?

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +    processing
?

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        return generators[generator_type]
what if `generation_type` > 3?

2023-12-17 06:53 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +        return self.__perplexity
add new line

2023-12-19 18:05 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 18:05 UTC, closed without merging