Laboratory work #3, Ulyana Abramova - 22FPL1
fipl-hse/2023-2-level-labs pull request #205
Opened 2023-12-10 14:14 UTC by ulyanaabr

2023-12-14 07:37 UTC, artyomtugaryov requested changes

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not len(text) == 0:
simplify

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        for id in corpus:
bad name

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        if not len(decoded_corpus) == 0:
bad condition

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +        return decoded_text + '.'
fstring

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
keep emply line

2023-12-14 07:37 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
.

2023-12-17 06:32 UTC, artyomtugaryov requested changes

2023-12-17 06:32 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
remove

2023-12-17 06:32 UTC, artyomtugaryov commented on lab_3_generate_by_ngrams/main.py
> +
remove rmpty line

2023-12-19 18:07 UTC, closed without merging

2023-12-19 18:07 UTC, vitazaytseva commented
Well done! Good job!