Laboratory work #4, Varvara Migacheva - 22FPL2
fipl-hse/2023-2-level-labs pull request #207
Opened 2023-12-11 21:47 UTC by varmig2000

2023-12-14 07:31 UTC, artyomtugaryov requested changes

2023-12-14 07:31 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
add error message

2023-12-14 07:31 UTC, artyomtugaryov commented on lab_4_fill_words_by_ngrams/main.py
> +                tokenized_text += ' ' + self._end_of_word_token
fstring

2023-12-14 07:32 UTC, artyomtugaryov requested changes
What about start.py ?

2023-12-17 00:28 UTC, varmig2000 commented on lab_4_fill_words_by_ngrams/main.py
> +            raise ValueError
fixed

2023-12-17 00:29 UTC, varmig2000 commented on lab_4_fill_words_by_ngrams/main.py
> +                tokenized_text += ' ' + self._end_of_word_token
fixed

2023-12-17 06:47 UTC, artyomtugaryov reviewed
Good job

2023-12-19 18:08 UTC, vitazaytseva commented
Well done! Good job!

2023-12-19 18:08 UTC, closed without merging