Laboratory Work #1, Egor Solovyev - 22FPL2
fipl-hse/2023-2-level-labs pull request #56
Opened 2023-09-21 20:28 UTC by egor-solo

2023-09-28 13:57 UTC, artyomtugaryov requested changes
Good start, hope you will be in time

2023-10-05 13:10 UTC, artyomtugaryov requested changes

2023-10-05 13:10 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
you do not `else` if you return in if

2023-10-05 13:10 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        for token in tokens:
try to do it in one line

2023-10-05 13:10 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    for token in tokens:
too many fors - merge it

2023-10-05 13:10 UTC, artyomtugaryov commented on main.py
> +
what is it? remove!

2023-10-05 20:46 UTC, egor-solo commented on main.py
> +
removed

2023-10-05 20:46 UTC, egor-solo commented on lab_1_classify_by_unigrams/main.py
> +    for token in tokens:
fixed

2023-10-05 20:46 UTC, egor-solo commented on lab_1_classify_by_unigrams/main.py
> +        for token in tokens:
done

2023-10-05 20:46 UTC, egor-solo commented on lab_1_classify_by_unigrams/main.py
> +    else:
removed

2023-10-08 16:37 UTC, closed without merging