Laboratory work #1, Evgeni Baronov - 22FPL2
fipl-hse/2023-2-level-labs pull request #59
Opened 2023-09-22 22:21 UTC by Baronofff

2023-09-28 14:13 UTC, marina-kaz requested changes
Not much to review today. Time to speed up :)

2023-09-28 14:13 UTC, marina-kaz commented on main.py
> +print('woow')
Hello! Welcome to the course!
Please do not push any extra files and work in the folder of the first lab.
Thank you!

2023-10-03 10:24 UTC, marina-kaz requested changes
No changes to review

2023-10-10 17:59 UTC, EIzharikov commented
Hello! Pay attention to the letter "в". There is probably an error in decoding, because there must be another one. 
You will succeed, good luck!

2023-10-12 13:34 UTC, marina-kaz reviewed
Some fixes and you are ready for your hand-in.

2023-10-12 13:34 UTC, marina-kaz commented on lab_1_classify_by_unigrams/main.py
> +    else:
Using `else` after the return statement is redundant.

2023-10-15 16:42 UTC, closed without merging