Laboratory work #2, Ulyana Nagornaya - 22FPL2
fipl-hse/2023-2-level-labs pull request #92
Opened 2023-10-12 09:41 UTC by Ulyana-Nagornaya

2023-10-12 11:47 UTC, artyomtugaryov requested changes
👀

2023-10-19 14:41 UTC, artyomtugaryov requested changes

2023-10-19 14:41 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> -
revert

2023-10-19 14:41 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        tokenized_words.append(word)
for what?

2023-10-31 14:03 UTC, artyomtugaryov requested changes

2023-10-31 14:03 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +        if f"'{pair[0]}', '{pair[1]}'" in str(word):
woow... Please, simplify

2023-10-31 14:03 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/target_score.txt
> +10
very good

2023-11-02 11:33 UTC, Ulyana-Nagornaya commented on lab_2_tokenize_by_bpe/main.py
> +        if f"'{pair[0]}', '{pair[1]}'" in str(word):
I`ve changed

2023-11-02 14:10 UTC, artyomtugaryov requested changes
Very nice

2023-11-02 14:10 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +            for token in word:
`.update`

2023-11-02 14:10 UTC, artyomtugaryov commented on lab_2_tokenize_by_bpe/main.py
> +                    decoded_sequence += end_of_word_token[end_index:] + ' '
is it replace?

2023-11-03 10:07 UTC, closed without merging